#--------------------------------------------------------#
#                       Deployment                       #
#--------------------------------------------------------#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "new-helm.fullname" . }}-nginx-deployment
  labels:
    {{- include "new-helm.labels" . | nindent 4 }}
    app: {{ .Values.nginxApp.labels.app }}
spec:
{{- if not .Values.nginxApp.autoscaling.enabled }}
  replicas: {{ .Values.nginxApp.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "new-helm.selectorLabels" . | nindent 6 }}
      app: {{ .Values.nginxApp.labels.app }}
  template:
    metadata:
      labels:
        {{- include "new-helm.selectorLabels" . | nindent 8 }}
        app: {{ .Values.nginxApp.labels.app }}
    spec:
      volumes:
      - name: {{ .Values.volumes.pv.name }}
        persistentVolumeClaim:
          claimName: {{ include "new-helm.fullname" . }}-pvc
      - name: {{ .Values.volumes.config.name }}
        configMap:
          name: {{ include "new-helm.fullname" . }}-nginx-config
          items:
          - key: {{ .Values.volumes.config.key }}
            path: {{ .Values.volumes.config.path }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.nginxApp.image.repository }}:{{ .Values.nginxApp.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.nginxApp.image.pullPolicy }}
          ports:
            - name: {{ .Values.nginxApp.ports.name }}
              containerPort: {{ .Values.nginxApp.ports.containerPort }}
              protocol: {{ .Values.nginxApp.ports.protocol }}
          livenessProbe:
            {{- toYaml .Values.nginxApp.livenessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.nginxApp.resources | nindent 12 }}
          volumeMounts:
            - name: {{ .Values.volumes.pv.name }}
              mountPath: {{ .Values.volumes.pv.mountPath }}
            - name: {{ .Values.volumes.config.name }}
              mountPath: {{ .Values.volumes.config.mountPath }}

---
#--------------------------------------------------------#
#                          Service                       #
#--------------------------------------------------------#

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginxApp.service.name }}
  labels:
    {{- include "new-helm.labels" . | nindent 4 }}
    app: {{ .Values.nginxApp.labels.app }}
spec:
  type: {{ .Values.nginxApp.service.type }}
  ports:
    - port: {{ .Values.nginxApp.service.port }}
      targetPort: {{ .Values.nginxApp.ports.containerPort }}
      protocol: {{ .Values.nginxApp.service.protocol }}
  selector:
    {{- include "new-helm.selectorLabels" . | nindent 4 }}
    app: {{ .Values.nginxApp.labels.app }}

---
#--------------------------------------------------------#
#                           HPA                          #
#--------------------------------------------------------#

{{- if .Values.nginxApp.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "new-helm.fullname" . }}-nginx-hpa
  labels:
    {{- include "new-helm.labels" . | nindent 4 }}
    app: {{ .Values.nginxApp.labels.app }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "new-helm.fullname" . }}-nginx-deployment
  minReplicas: {{ .Values.nginxApp.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.nginxApp.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.nginxApp.autoscaling.cpu.targetCPUUtilizationPercentage }}
    - type: {{ .Values.nginxApp.autoscaling.metrics.type }}
      resource:
        name: {{ .Values.nginxApp.autoscaling.cpu.name }}
        targetAverageUtilization: {{ .Values.nginxApp.autoscaling.cpu.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.nginxApp.autoscaling.memory.targetMemoryUtilizationPercentage }}
    - type: {{ .Values.nginxApp.autoscaling.metrics.type }}
      resource:
        name: {{ .Values.nginxApp.autoscaling.memory.name }}
        targetAverageUtilization: {{ .Values.nginxApp.autoscaling.memory.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}